name: Testing
values:
  - key: SERVER_ADDRESS
    value: 'http://localhost'
    enabled: true
  - key: SERVER_PORT
    value: '4000'
    enabled: true
  - key: API_VERSION
    value: v1
    enabled: true
  - key: TEST_OM_AUTH_TOKEN
    value: NTH5BYOPVS6WJ2XOK27W7Q6ZUH
    enabled: true
  - key: TEST_FD_AUTH_TOKEN
    value: UZPHDJXKVJORSLLQD7AH3QDCU3
    enabled: true
  - key: TEST_HK_AUTH_TOKEN
    value: UKAKGCKBNSDEJPYBN7S6LFZI3W
    enabled: true
