name: Testing
values:
  - key: SERVER_ADDRESS
    value: ''
    enabled: true
  - key: SERVER_PORT
    value: ''
    enabled: true
  - key: API_VERSION
    value: ''
    enabled: true
  - key: TEST_OM_AUTH_TOKEN
    value: ''
    enabled: true
  - key: TEST_FD_AUTH_TOKEN
    value: ''
    enabled: true
  - key: TEST_HK_AUTH_TOKEN
    value: ''
    enabled: true
